const COMPANY_NAMES = [
  'JPMorgan Chase',
  'Amazon',
  'UBS',
  'Bank of America',
  'Arcesium',
  'SAP',
  'Deloitte',
  'IBM',
  'Cognizant',
  'Accenture',
  'Capgemini',
  'Wipro',
  'RealPage',
  'HighRadius',
  'CDK Global',
  'Vitech Systems',
  'YASH Technologies',
  'Trianz',
  'Parexel',
  'Thryve Digital',
  'Carrier Technologies',
  'Ascensus',
  'OpenText',
  'Oracle',
  'ADP',
  'Dell',
  'Virtusa',
  'ValueLabs',
  'HCL',
  'Avineon India',
  'TEKsystems',
  'Quantela',
  'Megasoft',
  'Vertex Offshore Services',
  'Lantronix India',
  'Pennant Technologies',
  'Incipio Technologies',
  'Vilas Business Solutions',
  'Virpie Info Technologies',
  'Seanergy Digital Services',
  'Desidea Software Technologies',
  'Jointlook Services',
  'BostonLogix',
  'S2Tech',
  'Lanco Global Systems',
  'Vertex Computer Systems',
  'SmartPlay Technologies',
  'ZenQ',
  'CenturyLink',
  'MarketTools',
  'Sitel',
  'Salesforce',
  'GF Digital',
  'CenturyLink (Lumen)',
  'NTT DATA',
  'ABB',
  'Celigo',
  'Tech Mahindra',
  'Cambridge Technology',
  'Valyd Software',
  'Levadata',
  'Innopark',
  'SD Softech',
  'UMC',
  'eCentric Solutions',
  'RSA',
  'Valyd Info Solutions',
  'SmartDocs Technologies',
  'Covalense Digital',
  'Marlabs',
  'NXP Semiconductors',
  'Medtronic',
  'Collins Aerospace',
  'GlobalLogic',
  'Hitachi Solutions',
  'CGI',
  'Unisys',
  'Axtria',
  'Genpact',
  'Zensar',
  'GlobalLogic Technologies',
  'Sagility India (HGS Healthcare)',
  'TIBCO Software India',
  'Alight Solutions (NGA HR)',
  'DXC Technology India',
  'Microsoft',
  'Google',
  'Apple',
  'Meta',
  'NVIDIA',
  'Intel',
  'AMD',
  'Qualcomm',
  'Cisco',
  'Adobe',
  'VMware',
  'ServiceNow',
  'Atlassian',
  'Zoho',
  'Freshworks',
  'PayPal',
  'Walmart Global Tech',
  'Goldman Sachs',
  'Morgan Stanley',
  'American Express',
  'Visa',
  'Mastercard',
  'Flipkart',
  'Meesho',
  'PhonePe',
  'Razorpay',
  'CRED',
  'Swiggy',
  'Zomato',
  'Ola',
  'Uber',
  'InMobi',
  'Oracle Financial Services Software (OFSS)',
  'Intuit',
  'Synopsys',
  'Cadence',
  'Siemens',
  'Siemens Healthineers',
  'Honeywell',
  'Philips',
  'Bosch Global Software Technologies',
  'Schneider Electric',
  'GE Healthcare',
  'Ericsson',
  'Nokia',
  'Samsung R&D Institute India',
  'LG Soft India',
  'Harman',
  'Continental',
  'Aptiv',
  'Volvo Group',
  'Mercedes-Benz Research and Development India',
  'Renault Nissan Technology & Business Centre India',
  'Tata Elxsi',
  'LTIMindtree',
  'L&T Technology Services (LTTS)',
  'Mphasis',
  'Persistent Systems',
  'Hexaware Technologies',
  'Sonata Software',
  'Birlasoft',
  'KPIT Technologies',
  'Cyient',
  'Coforge',
  'UST',
  'Brillio',
  'Happiest Minds',
  'Nagarro',
  'Newgen Software',
  'CitiusTech',
  'Fiserv',
  'FIS',
  'Fidelity Investments',
  'FactSet',
  'Broadridge',
  'Western Digital',
  'Micron Technology',
  'AMDOCS',
  'McKinsey & Company',
  'Bain & Company',
  'KPMG',
  'EY',
  'PwC',
  'Grant Thornton',
  'RSM',
  'Ericsson India',
  'Juniper Networks',
  'Red Hat',
  'SAP Labs India',
  'Informatica',
  'Nutanix',
  'Rubrik',
  'Cohesity',
  'Cloudera',
  'Snowflake',
  'Palo Alto Networks',
  'CrowdStrike',
  'Check Point Software Technologies',
  'Fortinet',
  'Cloudflare',
  'Expedia Group',
  'Agoda',
  'Booking.com',
  'BlackRock',
  'Shell',
  'BP',
  'ExxonMobil',
  'Shell Info Technologies',
  'PepsiCo Global Business Services',
  'Unilever',
  'Procter & Gamble (P&G)',
  'Reckitt',
  'Mondelez International',
  'PepsiCo',
  'Johnson Controls',
  'Optum',
  'UnitedHealth Group',
  'Cerner (Oracle Health)',
  'Epic Systems',
  'AstraZeneca',
  'Novartis',
  'Roche',
  'Pfizer',
  'Eli Lilly',
  'Sanofi',
  "Dr. Reddy's Laboratories",
  'Biocon',
  'IQVIA',
  'Deloitte USI',
  'EY GDS',
  'PwC India',
  'KPMG India',
  'BNY',
  'State Street',
  'Barclays',
  'HSBC',
  'Standard Chartered',
  'NatWest Group',
  'Deutsche Bank',
  'Societe Generale',
  'Wells Fargo',
  'Northern Trust',
  'TCS',
  'Infosys',
  'HCLTech',
];

const slugifyCompany = (name) =>
  name
    .toLowerCase()
    .replace(/&/g, ' and ')
    .replace(/\+/g, ' plus ')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');

const uniqueCompanies = Array.from(
  new Map(COMPANY_NAMES.map((name) => [slugifyCompany(name), name])).entries(),
).map(([value, label]) => ({ value, label }));

export const COMPANY_OPTIONS = [
  { value: '', label: 'No specific company' },
  ...uniqueCompanies.sort((a, b) => a.label.localeCompare(b.label)),
];
